name: "Build and Push to DockerHub"

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Login a DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build y push a DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            aixa949/as241s5_aej_10-be:latest
            aixa949/as241s5_aej_10-be:${{ github.sha }}