name: "Notificacion a Slack"

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Enviar notificacion a Slack
        uses: slackapi/slack-github-action@v1.26
        with:
          payload: |
            {
              "text": "Pipeline completado - Repositorio: ${{ github.repository }} - Rama: ${{ github.ref_name }} - Autor: ${{ github.actor }} - Estado: Exitoso - Ver: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}